social/accounts/urls.py
from django.urls import path
from .views import (
    show_profile,
    feed,
    follows_list,
    followers_list,
    follows,
    stop_follow,
    postLikeToggle,
    PostDetails
)

app_name = 'accounts'

urlpatterns = [
    path('', feed, name='feed'),
    path('<int:id>/', PostDetails , name='postDetails'),  
    path('like/', postLikeToggle, name='likePost'),
    path('<str:username>/', show_profile, name="profile"),
    path('<str:username>/followed_to', follows_list, name='follow_list'),
    path('<str:username>/followed_by', followers_list, name='followers_list'),
    path('<str:username>/follows', follows, name='follows'),
    path('<str:username>/stop_follow', stop_follow, name='stop_follow'),
]

social/social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts.views import (
    home,
    auth_login,
    auth_register,
    auth_logout,
    activate,
)




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('login/', auth_login, name="login"),
    path('register/', auth_register, name="register"),
    path('logout/', auth_logout, name='logout'),
    path('feed/', include("accounts.urls", namespace='feed' )),
    path('donation/', include("donation.urls", namespace="donation")),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
]

if settings.DEBUG == True:
    urlpatterns = urlpatterns + static(
            settings.STATIC_URL, document_root=settings.STATIC_ROOT
        )
    urlpatterns = urlpatterns + static(
                settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
            )

social/templates/base/css.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/animation.css' %}">

social/templates/base/js.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="{% static 'js/style.js' %}"></script>
<script src="{% static 'js/like.js' %}"></script>

social/templates/base/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
<div class="container">
  <a class="navbar-brand" href="#"><img src="{% static 'img/logo.svg' %}" width="60px" height="60px"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Social</a>
      </li>

      {% if request.user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:profile' request.user.username %}">Profile</a>
      </li>


       <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>

      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="/#contact">Contact</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>

       <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">SignUp</a>
      </li>

      {% endif %}

    </ul>
  </div>
</div>
</nav>