social/donation/urls.py
from django.urls import path
from . import views


app_name = 'donation'

urlpatterns = [
    path('', views.Donation.as_view(), name='donation'),
    path('charge/', views.charge, name='charge'),
]

social/social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts.views import (
    home,
    auth_login,
    auth_register,
    auth_logout,
    activate,
)




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('login/', auth_login, name="login"),
    path('register/', auth_register, name="register"),
    path('logout/', auth_logout, name='logout'),
    path('feed/', include("accounts.urls", namespace='feed' )),
    path('donation/', include("donation.urls", namespace="donation")),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
]

if settings.DEBUG == True:
    urlpatterns = urlpatterns + static(
            settings.STATIC_URL, document_root=settings.STATIC_ROOT
        )
    urlpatterns = urlpatterns + static(
                settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
            )

social/donation/models.py
from django.db import models

# Create your models here.

social/donation/views.py
import stripe
from django.shortcuts import render
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

stripe.api_key = settings.STRIPE_SECRET_KEY

class Donation(TemplateView):
    template_name = 'donation/home.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["key"] = settings.STRIPE_PUBLISHABLE_KEY
        return context

@login_required
def charge(request):
    if request.method == "POST":

        charge = stripe.Charge.create(
            amount = 100,
            currency = 'usd',
            source = request.POST["stripeToken"],
            description = "donation from {donator}".format(donator=request.POST["stripeEmail"])            
        )
        return render(request, "donation/charge.html", {})

social/donation/templates/donation/charge.html
{% extends 'base.html' %}

{% block content %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Thanks</strong> You donated money will soon be transfered to your friend.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<a href="{% url 'home' %}"><button class="btn btn-success">Get Back</button></a>
{% endblock %}

social/donation/templates/donation/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<h1>Donate $1</h1>

<form action="{% url 'donation:charge' %}" method="POST">
{% csrf_token %}
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key = "{{ key }}" 
    data-desciption = "Donation towards the player"
    data-amount = "100"
    data-locale = auto>
</script>
</form>
{% endblock %}